#pragma once

// optimisations for boot time
//#ifndef NO_DEBUG
//#define NO_DEBUG
//#endif
//#ifndef NO_PRINT
//#define NO_PRINT
//#endif

#ifdef RGB_MATRIX_ENABLE

#  define RGB_MATRIX_TIMEOUT 300000  // 5 min

// hard-coded colors for caps lock and fn layer
#  define CAPS_LOCK_INDICATOR_COLOR_RGB RGB_RED
#  define FN_LAYER_COLOR_RGB RGB_GREEN

#  define RGB_MATRIX_KEYREACTIVE_ENABLED

// enable effects we want
#  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#  define ENABLE_RGB_MATRIX_SOLID_COLOR
#  define ENABLE_RGB_MATRIX_SOLID_REACTIVE_BACKLIGHT
// set default effect
#  define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CUSTOM_SOLID_REACTIVE_BACKLIGHT
// disable ones we don't care about, to reduce bloat
#  undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#  undef ENABLE_RGB_MATRIX_BREATHING
#  undef ENABLE_RGB_MATRIX_CYCLE_ALL
#  undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#  undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#  undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#  undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#  undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#  undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#  undef ENABLE_RGB_MATRIX_DIGITAL_RAIN
#  undef ENABLE_RGB_MATRIX_DUAL_BEACON
#  undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#  undef ENABLE_RGB_MATRIX_PIXEL_RAIN
#  undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#  undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#  undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#  undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#  undef ENABLE_RGB_MATRIX_SOLID_SPLASH
#  undef ENABLE_RGB_MATRIX_SPLASH
#  undef ENABLE_RGB_MATRIX_TYPING_HEATMAP

#endif //RGB_MATRIX_ENABLE